// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAE6-nGbHUl_2pMYkH8XmzXJrDkPuyfDKw',
    appId: '1:445562797903:web:2f5f4340a50c1dc5dc0f3a',
    messagingSenderId: '445562797903',
    projectId: 'ergobug',
    authDomain: 'ergobug.firebaseapp.com',
    storageBucket: 'ergobug.firebasestorage.app',
    measurementId: 'G-CVTR6V6LLS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBalFXKjWJ-I5BIRdtiiteASggS34XQrk',
    appId: '1:445562797903:android:139ec8fbfae38951dc0f3a',
    messagingSenderId: '445562797903',
    projectId: 'ergobug',
    storageBucket: 'ergobug.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCw2sUF3_f75-KOq4nGcuO7MBgkqC1MJq8',
    appId: '1:445562797903:ios:3ec87fa557f8074fdc0f3a',
    messagingSenderId: '445562797903',
    projectId: 'ergobug',
    storageBucket: 'ergobug.firebasestorage.app',
    iosBundleId: 'com.example.studentTaskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCw2sUF3_f75-KOq4nGcuO7MBgkqC1MJq8',
    appId: '1:445562797903:ios:3ec87fa557f8074fdc0f3a',
    messagingSenderId: '445562797903',
    projectId: 'ergobug',
    storageBucket: 'ergobug.firebasestorage.app',
    iosBundleId: 'com.example.studentTaskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAE6-nGbHUl_2pMYkH8XmzXJrDkPuyfDKw',
    appId: '1:445562797903:web:b052a0a02c34c23cdc0f3a',
    messagingSenderId: '445562797903',
    projectId: 'ergobug',
    authDomain: 'ergobug.firebaseapp.com',
    storageBucket: 'ergobug.firebasestorage.app',
    measurementId: 'G-WGMW99PTKQ',
  );
}
